Repository emacs-lsp/lsp-ui, pull requests merged in 2022-04, with the labels that each got.

#699 Doc wrap now adjusts to text scale
  lsp-ui-doc.el
Labels: ui-doc

#700 Use Eask for CI
  .github/workflows/test.yml
  .gitignore
  Cask
  Eask
  Makefile
  test/windows-bootstrap.el
Labels: CI

#703 Use merged setup-emacs action
  .github/workflows/test.yml
Labels: CI

#669 Add additional info to lsp-ui-doc-enable docs
  lsp-ui-doc.el
Labels: documentation
